import type { Metadata } from 'next'
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import Image from "next/image";
import Link from 'next/link';
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <header className="flex justify-between items-center p-4 gap-4 h-16 drop-shadow-2xl bg-surface">
            <div>
              <Link href={"/"}>
                <Image src={"/images/lumio/lumio-64x64.png"} height={48} width={48} alt='Lumio character' />
              </Link>
            </div>

            <div>
              <Show when="signed-out">
                <SignInButton>
                  <button className="rounded-full font-medium text-sm sm:text-base py-1 px-6 cursor-pointer">
                    Sign In
                  </button>
                </SignInButton>

                <SignUpButton>
                  <button className="bg-brand text-white rounded-full font-medium text-sm sm:text-base py-1 px-6 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </Show>

              <Show when="signed-in">
                <UserButton />
              </Show>
            </div>
          </header>

          {children}
        </ClerkProvider>
      </body>
    </html>
  )
}